[package]
name = "quark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test = [ "async-std", "mongodb/async-std-runtime" ]
default = [ "test" ]

[dependencies]
# Serialisation
serde = { version = "1", features = ["derive"] }

# Databases
mongodb = { version = "2.1.0", default-features = false }

# Async
async-trait = "0.1.51"
async-std = { version = "1.8.0", features = ["attributes"], optional = true }

# Logging
log = "0.4"
