[package]
name = "revolt-quark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test = [ "async-std", "mongodb/async-std-runtime" ]
default = [ "test" ]

[dependencies]
# Serialisation
optional_struct = { git = "https://github.com/insertish/OptionalStruct", rev = "2011de17db6ecb210fddabe3d79ade865efaf4ee" }
serde = { version = "1", features = ["derive"] }
validator = { version = "0.14", features = ["derive"] }

# Databases
mongodb = { version = "2.1.0", default-features = false }

# Async
async-trait = "0.1.51"
async-std = { version = "1.8.0", features = ["attributes"], optional = true }

# Logging
log = "0.4"

# Util
ops = "0.6.0"
impl_ops = "0.1.1"
num_enum = "0.5.6"
lazy_static = "1.4.0"
