version: '3.3'
services:
    redis:
        image: eqalpha/keydb
        ports:
            - "6379:6379"
    database:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./.data:/data/db
    minio:
        image: minio/minio
        command: server /data
        environment:
            MINIO_ROOT_USER: minioautumn
            MINIO_ROOT_PASSWORD: minioautumn
        ports:
            - "9050:9000"
            - "40209:40209"
        volumes:
            - ./.minio:/data
    # createbuckets:
    #     image: minio/mc
    #     depends_on:
    #         - minio
    #     env_file: .env
    #     entrypoint: >
    #       /bin/sh -c "
    #       while ! curl -s --output /dev/null --connect-timeout 1 http://minio:9000; do echo 'Waiting for minio...' && sleep 0.1; done;
    #       /usr/bin/mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
    #       /usr/bin/mc mb minio/avatars;
    #       /usr/bin/mc mb minio/banners;
    #       /usr/bin/mc mb minio/covers;
    #       /usr/bin/mc mb minio/emoji;
    #       exit 0;
    #       "
    # autumn:
    #     image: revoltchat/autumn
    #     env_file: .env
    #     depends_on:
    #         - database
    #         - createbuckets
    #     environment:
    #         - AUTUMN_MONGO_URI=mongodb://database
    #     ports:
    #         - "3030:3000"
    #     volumes:
    #         - ./Autumn.toml:/Autumn.toml
    #     restart: always
